name: Pokemon Card Stock Alarm v2

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Run stock checker
        run: |
          python pokemon_alarm.py
